### ISSUE TITLE
are there some real-world examples somewhere?

### ISSUE THREAD

**Issue by UnixJunkie** [let-def/inuit#3]
Is it production-ready?
I use '\r' instead of '\n' in my printf strings for the same purpose currently.

**Comment by let-def** [comment]
Yes it is but there is a catch: the only backend implemented is in the form of an emacs buffer, there is no support for terminal as of today (I wish, but I postponed and emacs was good enough for my use).

You can find the emacs backend here: https://github.com/let-def/sturgeon/ and some examples there : https://github.com/let-def/sturgeon/tree/master/test .

`inuit` is just the abstraction for manipulating text, `sturgeon` is a toolkit for interacting with emacs from ocaml.

There is one external user there: https://github.com/jhjourdan/statmemprof-emacs . It is a live frontend to the very good statistical memory profiler by jhjourdan.

**Comment by UnixJunkie** [comment]
OK, I might use something else in the future then.
My main goal is to pilot terminals (xterm and friends).
I saw some special libraries for that but I don't remember if they were in ocaml.
Thanks for your answer.

**Comment by let-def** [comment]
You can look at https://github.com/pqwy/notty : it is a bit more involved, but it is much more expressive. If it fits your needs, it is a very good library.
The ideal would be to have an library that uses notty for the most part and inuit for managing text :-)

**Comment by UnixJunkie** [comment]
wow, their asciinema demos are pretty cool
